"""
Auto-generated by Build Agent
Original: pylabrobot/heating_shaking/bioshake_backend.py

[UNILAB DEBUG] 此驱动已注入调试日志
- 每个方法被调用时会打印日志
- 日志格式: [UNILAB] ClassName.method_name() called
- 查看日志: logging.getLogger("unilab.driver").setLevel(logging.DEBUG)
"""
from unilabos.registry.decorators import action, device
from typing import Dict, Any, Optional
import logging
import warnings as _warnings
_warnings.filterwarnings("ignore", message=r"pkg_resources is deprecated as an API\..*")
import sys as _sys
import types as _types

# 兼容性：部分上游框架（例如 lantz）在 import-time 强制加载 Qt（PyQt4/PySide1），
# 在 headless/现代 Python 环境中通常不存在这些绑定，会导致导入直接失败。
# 这里预注入一个最小的 `lantz.utils.qt` shim，避免触发其 Qt loader。
if "lantz.utils.qt" not in _sys.modules:
    _qt_mod = _types.ModuleType("lantz.utils.qt")

    class _DummyQtCore:
        class QObject:
            def __init__(self, *_args, **_kwargs):
                # 兼容 QObject(parent=...) 等调用
                return None

        @staticmethod
        def Signal(*_args, **_kwargs):
            return object()

        @staticmethod
        def Slot(*_args, **_kwargs):
            def _decorator(fn):
                return fn

            return _decorator

    _qt_mod.QtCore = _DummyQtCore

    class _DummySuperQObject(_DummyQtCore.QObject):
        def __new__(cls, *_args, **_kwargs):
            return super().__new__(cls)

        def __init__(self, *_args, **_kwargs):
            # 允许 Driver(...) 传参，不触发 object.__init__ 的 TypeError
            return None

    _qt_mod.MetaQObject = type
    _qt_mod.SuperQObject = _DummySuperQObject
    _sys.modules["lantz.utils.qt"] = _qt_mod

# Unilab 驱动调试日志
_unilab_logger = logging.getLogger("unilab.driver.BioShake")
_unilab_logger.setLevel(logging.DEBUG)
if not _unilab_logger.handlers:
    _handler = logging.StreamHandler()
    _handler.setFormatter(logging.Formatter("[%(asctime)s] %(message)s"))
    _unilab_logger.addHandler(_handler)

# Vendored repo packages: pylabrobot, pylabrobot
import sys as _sys
from pathlib import Path as _Path
_vendor_root = _Path(__file__).resolve().parent / "_vendor"
if _vendor_root.exists() and str(_vendor_root) not in _sys.path:
    _sys.path.insert(0, str(_vendor_root))

import asyncio

from pylabrobot.heating_shaking.backend import HeaterShakerBackend
from pylabrobot.io.serial import Serial
from pylabrobot.machines.backend import MachineBackend

try:
  import serial

  HAS_SERIAL = True
except ImportError as e:
  HAS_SERIAL = False
  _SERIAL_IMPORT_ERROR = e


@device(
  id="bio_shake",
  category=["Thermomixer", "Microplate Thermoshaker"],
  description="这是一种实验室微孔板加热振荡器，可对板式样品进行控温并同时振荡混匀。它常用于样品孵育、反应混合、酶反应、核酸与蛋白相关实验等需要稳定温度和持续摇匀的流程，部分机型还支持锁板与主动冷却功能。",
)
class BioShake(HeaterShakerBackend):
  def __init__(self, port: str, timeout: int = 60):
    print("[UNILAB] BioShake.__init__() called", flush=True)
    if not HAS_SERIAL:
      raise RuntimeError(
        f"pyserial is required for the BioShake module backend. Import error: {_SERIAL_IMPORT_ERROR}"
      )

    self.setup_finished = False
    self.port = port
    self.timeout = timeout
    self.io = Serial(
      port=self.port,
      baudrate=9600,
      bytesize=serial.EIGHTBITS,
      parity=serial.PARITY_NONE,
      stopbits=serial.STOPBITS_ONE,
      write_timeout=10,
      timeout=self.timeout,
    )

  async def _send_command(self, cmd: str, delay: float = 0.5, timeout: float = 2):
    _unilab_logger.debug("[UNILAB] BioShake._send_command() called")
    try:
      # Flush serial buffers for a clean start
      await self.io.reset_input_buffer()
      await self.io.reset_output_buffer()

      # Send the command
      await self.io.write((cmd + "\r").encode("ascii"))
      await asyncio.sleep(delay)

      # Read and decode the response with a timeout
      try:
        response = await asyncio.wait_for(self.io.readline(), timeout=timeout)

      except asyncio.TimeoutError:
        raise RuntimeError(f"Timed out waiting for response to '{cmd}'")

      decoded = response.decode("ascii", errors="ignore").strip()

      # Parsing the response from the BioShake

      # No response at all
      if not decoded:
        raise RuntimeError(f"No response for '{cmd}'")

      # Device-specific errors
      if decoded.startswith("e"):
        raise RuntimeError(f"Device returned error for '{cmd}': '{decoded}'")

      if decoded.startswith("u ->"):
        raise NotImplementedError(f"'{cmd}' not supported: '{decoded}'")

      # Standard OK
      if decoded.lower().startswith("ok"):
        return None

      # All other valid responses (e.g. temperature and remaining time)
      return decoded

    except Exception as e:
      raise RuntimeError(f"Unexpected error while sending '{cmd}': {type(e).__name__}: {e}") from e

  @action(auto_prefix=True, description="初始化设备并准备运行")
  async def setup(self, skip_home: bool = False):
    _unilab_logger.debug("[UNILAB] BioShake.setup() called")
    await MachineBackend.setup(self)
    await self.io.setup()
    if not skip_home:
      # Reset first before homing it to ensure the device is ready for run
      await self.reset()
      # Additional seconds until next command can be send after reset
      await asyncio.sleep(4)
      # Now home the device
      await self.home()

  @action(auto_prefix=True, description="停止设备运行")
  async def stop(self):
    _unilab_logger.debug("[UNILAB] BioShake.stop() called")
    await MachineBackend.stop(self)
    await self.io.stop()

  @action(auto_prefix=True, description="复位设备")
  async def reset(self):
    _unilab_logger.debug("[UNILAB] BioShake.reset() called")
    # Reset the BioShake if stuck in "e" state
    # Flush serial buffers for a clean start
    await self.io.reset_input_buffer()
    await self.io.reset_output_buffer()

    # Send the command
    await self.io.write(("resetDevice\r").encode("ascii"))

    start = asyncio.get_event_loop().time()
    max_seconds = 30  # How long a reset typically last

    while True:
      # Break the loop if process takes longer than 30 seconds
      if asyncio.get_event_loop().time() - start > max_seconds:
        raise TimeoutError("Reset did not complete in time")

      try:
        # Wait for each line with a timeout
        response = await asyncio.wait_for(self.io.readline(), timeout=2)
        decoded = response.decode("ascii", errors="ignore").strip()
        await asyncio.sleep(0.1)

        if len(decoded) > 0:
          # Stop when the final message arrives
          if "Initialization complete" in decoded:
            break

      except asyncio.TimeoutError:
        # Keep polling if nothing arrives within timeout
        continue

  @action(auto_prefix=True, description="回到初始位置")
  async def home(self):
    _unilab_logger.debug("[UNILAB] BioShake.home() called")
    # Initialize the BioShake into home position
    await self._send_command(cmd="shakeGoHome", delay=5)

  @action(auto_prefix=True, description="以设定速度开始振荡")
  async def shake(self, speed: float, acceleration: int = 0):
    _unilab_logger.debug("[UNILAB] BioShake.shake() called")
    # Check if speed is an integer
    if isinstance(speed, float):
      if not speed.is_integer():
        raise ValueError(f"Speed must be a whole number, not {speed}")
      speed = int(speed)
    if not isinstance(speed, int):
      raise TypeError(
        f"Speed must be an integer or a whole number float, not {type(speed).__name__}"
      )

    # Get the min and max speed of the device to assert speed
    min_speed = int(float(await self._send_command(cmd="getShakeMinRpm", delay=0.2)))
    max_speed = int(float(await self._send_command(cmd="getShakeMaxRpm", delay=0.2)))

    assert (
      min_speed <= speed <= max_speed
    ), f"Speed {speed} RPM is out of range. Allowed range is {min_speed}{max_speed} RPM"

    # Set the speed of the shaker
    set_speed_cmd = f"setShakeTargetSpeed{speed}"
    await self._send_command(cmd=set_speed_cmd)

    # Check if accel is an integer
    if isinstance(acceleration, float):
      if not acceleration.is_integer():  # type: ignore[attr-defined] # mypy is retarded
        raise ValueError(f"Acceleration must be a whole number, not {acceleration}")
      acceleration = int(acceleration)
    if not isinstance(acceleration, int):
      raise TypeError(
        f"Acceleration must be an integer or a whole number float, not {type(acceleration).__name__}"
      )

    # Get the min and max acceleration of the device to check bounds
    min_accel = int(float(await self._send_command(cmd="getShakeAccelerationMin", delay=0.2)))
    max_accel = int(float(await self._send_command(cmd="getShakeAccelerationMax", delay=0.2)))

    assert (
      min_accel <= acceleration <= max_accel
    ), f"Acceleration {acceleration} seconds is out of range. Allowed range is {min_accel}-{max_accel} seconds"

    # Set the acceleration of the shaker
    set_accel_cmd = f"setShakeAcceleration{acceleration}"
    await self._send_command(cmd=set_accel_cmd, delay=0.2)

    # Send the command to start shaking, either with or without duration

    await self._send_command(cmd="shakeOn", delay=0.2)

  @action(auto_prefix=True, description="停止振荡")
  async def stop_shaking(self, deceleration: int = 0):
    _unilab_logger.debug("[UNILAB] BioShake.stop_shaking() called")
    # Check if decel is an integer
    if isinstance(deceleration, float):
      if not deceleration.is_integer():  # type: ignore[attr-defined] # mypy is retarded
        raise ValueError(f"Deceleration must be a whole number, not {deceleration}")
      deceleration = int(deceleration)
    if not isinstance(deceleration, int):
      raise TypeError(
        f"Deceleration must be an integer or a whole number float, not {type(deceleration).__name__}"
      )

    # Get the min and max decel of the device to asset decel
    min_decel = int(float(await self._send_command(cmd="getShakeAccelerationMin", delay=0.2)))
    max_decel = int(float(await self._send_command(cmd="getShakeAccelerationMax", delay=0.2)))

    assert (
      min_decel <= deceleration <= max_decel
    ), f"Deceleration {deceleration} seconds is out of range. Allowed range is {min_decel}-{max_decel} seconds"

    # Set the deceleration of the shaker
    set_decel_cmd = f"setShakeAcceleration{deceleration}"
    await self._send_command(cmd=set_decel_cmd, delay=0.2)

    # stop shaking
    await self._send_command(cmd="shakeOff", delay=0.2)

  @property
  @action(auto_prefix=True, description="获取是否支持锁板")
  def supports_locking(self) -> bool:
    _unilab_logger.debug("[UNILAB] BioShake.supports_locking() called")
    return True

  @action(auto_prefix=True, description="锁定样品板")
  async def lock_plate(self):
    _unilab_logger.debug("[UNILAB] BioShake.lock_plate() called")
    await self._send_command(cmd="setElmLockPos", delay=0.3)

  @action(auto_prefix=True, description="解锁样品板")
  async def unlock_plate(self):
    _unilab_logger.debug("[UNILAB] BioShake.unlock_plate() called")
    await self._send_command(cmd="setElmUnlockPos", delay=0.3)

  @property
  @action(auto_prefix=True, description="获取是否支持主动冷却")
  def supports_active_cooling(self) -> bool:
    _unilab_logger.debug("[UNILAB] BioShake.supports_active_cooling() called")
    return True

  @action(auto_prefix=True, description="设置目标温度")
  async def set_temperature(self, temperature: float):
    _unilab_logger.debug("[UNILAB] BioShake.set_temperature() called")
    # Get the min and max set points of the device to assert temperature
    min_temp = int(float(await self._send_command(cmd="getTempMin", delay=0.2)))
    max_temp = int(float(await self._send_command(cmd="getTempMax", delay=0.2)))

    assert (
      min_temp <= temperature <= max_temp
    ), f"Temperature {temperature} C is out of range. Allowed range is {min_temp}–{max_temp} C."

    temperature = temperature * 10

    # Check if temperature is an integer
    if isinstance(temperature, float):
      if not temperature.is_integer():
        raise ValueError(f"Temperature must be a whole number, not {temperature} (1/10 C)")
      temperature = int(temperature)
    if not isinstance(temperature, int):
      raise TypeError(
        f"Temperature must be an integer or a whole number float, not {type(temperature).__name__} (1/10 C)"
      )

    set_temp_cmd = f"setTempTarget{temperature}"
    await self._send_command(cmd=set_temp_cmd, delay=0.2)

    # Start temperature control
    await self._send_command(cmd="tempOn", delay=0.2)

  @action(auto_prefix=True, description="获取当前温度")
  async def get_current_temperature(self) -> float:
    _unilab_logger.debug("[UNILAB] BioShake.get_current_temperature() called")
    response = await self._send_command(cmd="getTempActual", delay=0.2)
    return float(response)

  @action(auto_prefix=True, description="关闭温控")
  async def deactivate(self):
    _unilab_logger.debug("[UNILAB] BioShake.deactivate() called")
    # Stop temperature control
    await self._send_command(cmd="tempOff", delay=0.2)
