"""
Auto-generated by Build Agent
Original: pylabrobot/centrifuge/centrifuge.py

[UNILAB DEBUG] 此驱动已注入调试日志
- 每个方法被调用时会打印日志
- 日志格式: [UNILAB] ClassName.method_name() called
- 查看日志: logging.getLogger("unilab.driver").setLevel(logging.DEBUG)
"""
from unilabos.registry.decorators import action, device
from typing import Dict, Any, Optional
import logging
import warnings as _warnings
_warnings.filterwarnings("ignore", message=r"pkg_resources is deprecated as an API\..*")
import sys as _sys
import types as _types

# 兼容性：部分上游框架（例如 lantz）在 import-time 强制加载 Qt（PyQt4/PySide1），
# 在 headless/现代 Python 环境中通常不存在这些绑定，会导致导入直接失败。
# 这里预注入一个最小的 `lantz.utils.qt` shim，避免触发其 Qt loader。
if "lantz.utils.qt" not in _sys.modules:
    _qt_mod = _types.ModuleType("lantz.utils.qt")

    class _DummyQtCore:
        class QObject:
            def __init__(self, *_args, **_kwargs):
                # 兼容 QObject(parent=...) 等调用
                return None

        @staticmethod
        def Signal(*_args, **_kwargs):
            return object()

        @staticmethod
        def Slot(*_args, **_kwargs):
            def _decorator(fn):
                return fn

            return _decorator

    _qt_mod.QtCore = _DummyQtCore

    class _DummySuperQObject(_DummyQtCore.QObject):
        def __new__(cls, *_args, **_kwargs):
            return super().__new__(cls)

        def __init__(self, *_args, **_kwargs):
            # 允许 Driver(...) 传参，不触发 object.__init__ 的 TypeError
            return None

    _qt_mod.MetaQObject = type
    _qt_mod.SuperQObject = _DummySuperQObject
    _sys.modules["lantz.utils.qt"] = _qt_mod

# Unilab 驱动调试日志
_unilab_logger = logging.getLogger("unilab.driver.Centrifuge")
_unilab_logger.setLevel(logging.DEBUG)
if not _unilab_logger.handlers:
    _handler = logging.StreamHandler()
    _handler.setFormatter(logging.Formatter("[%(asctime)s] %(message)s"))
    _unilab_logger.addHandler(_handler)

# Vendored repo packages: pylabrobot, pylabrobot
import sys as _sys
from pathlib import Path as _Path
_vendor_root = _Path(__file__).resolve().parent / "_vendor"
if _vendor_root.exists() and str(_vendor_root) not in _sys.path:
    _sys.path.insert(0, str(_vendor_root))

import warnings
from typing import Optional, Tuple

from pylabrobot.centrifuge.backend import CentrifugeBackend, LoaderBackend
from pylabrobot.centrifuge.standard import (
  BucketHasPlateError,
  BucketNoPlateError,
  CentrifugeDoorError,
  LoaderNoPlateError,
  NotAtBucketError,
)
from pylabrobot.machines.machine import Machine
from pylabrobot.resources import Coordinate, Resource, ResourceHolder
from pylabrobot.resources.rotation import Rotation
from pylabrobot.serializer import deserialize


@device(
  id="centrifuge",
  category=["Centrifuge"],
  description="实验室离心机利用离心力分离液体样品中的不同组分，常用于样品沉降、相分离和前处理。该设备具备舱门控制、转篮/吊篮位置切换，以及按设定离心力和时间执行离心循环的能力，可用于自动化样品处理流程。",
)
class Centrifuge(Machine, Resource):
  """The front end for centrifuges."""

  def __init__(
    self,
    backend: CentrifugeBackend,
    name: str,
    size_x: float,
    size_y: float,
    size_z: float,
    rotation: Optional[Rotation] = None,
    category: Optional[str] = "centrifuge",
    model: Optional[str] = None,
    buckets: Optional[Tuple[ResourceHolder, ResourceHolder]] = None,
  ) -> None:
    print("[UNILAB] Centrifuge.__init__() called", flush=True)
    Machine.__init__(self, backend=backend)
    Resource.__init__(
      self,
      name=name,
      size_x=size_x,
      size_y=size_y,
      size_z=size_z,
      rotation=rotation,
      category=category,
      model=model,
    )
    self.backend: CentrifugeBackend = backend  # fix type
    self._door_open = False
    self._at_bucket: Optional[ResourceHolder] = None
    if buckets is None:
      self.bucket1 = ResourceHolder(
        name=f"{name}_bucket1",
        size_x=127.76,
        size_y=85.48,
        size_z=0,
        child_location=Coordinate.zero(),
      )
      self.bucket2 = ResourceHolder(
        name=f"{name}_bucket2",
        size_x=127.76,
        size_y=85.48,
        size_z=0,
        child_location=Coordinate.zero(),
      )
    else:
      self.bucket1, self.bucket2 = buckets
    # TODO: figure out good locations for this.
    self.assign_child_resource(self.bucket1, location=Coordinate.zero())
    self.assign_child_resource(self.bucket2, location=Coordinate.zero())

  @action(auto_prefix=True, description="打开离心机门。")
  async def open_door(self) -> None:
    _unilab_logger.debug("[UNILAB] Centrifuge.open_door() called")
    await self.backend.open_door()
    self._door_open = True

  @action(auto_prefix=True, description="关闭离心机门。")
  async def close_door(self) -> None:
    _unilab_logger.debug("[UNILAB] Centrifuge.close_door() called")
    await self.backend.close_door()
    self._door_open = False

  @property
  @action(auto_prefix=True, description="获取离心机门是否打开。")
  def door_open(self) -> bool:
    _unilab_logger.debug("[UNILAB] Centrifuge.door_open() called")
    return self._door_open

  @action(auto_prefix=True, description="锁定离心机门。")
  async def lock_door(self) -> None:
    _unilab_logger.debug("[UNILAB] Centrifuge.lock_door() called")
    await self.backend.lock_door()

  @action(auto_prefix=True, description="解锁离心机门。")
  async def unlock_door(self) -> None:
    _unilab_logger.debug("[UNILAB] Centrifuge.unlock_door() called")
    await self.backend.unlock_door()

  @action(auto_prefix=True, description="解锁转篮/吊篮。")
  async def unlock_bucket(self) -> None:
    _unilab_logger.debug("[UNILAB] Centrifuge.unlock_bucket() called")
    await self.backend.unlock_bucket()

  @action(auto_prefix=True, description="锁定转篮/吊篮。")
  async def lock_bucket(self) -> None:
    _unilab_logger.debug("[UNILAB] Centrifuge.lock_bucket() called")
    await self.backend.lock_bucket()

  @action(auto_prefix=True, description="将转子定位到 1 号转篮/吊篮位置。")
  async def go_to_bucket1(self, **backend_kwargs) -> None:
    _unilab_logger.debug("[UNILAB] Centrifuge.go_to_bucket1() called")
    await self.backend.go_to_bucket1(**backend_kwargs)
    self._at_bucket = self.bucket1

  @action(auto_prefix=True, description="将转子定位到 2 号转篮/吊篮位置。")
  async def go_to_bucket2(self, **backend_kwargs) -> None:
    _unilab_logger.debug("[UNILAB] Centrifuge.go_to_bucket2() called")
    await self.backend.go_to_bucket2(**backend_kwargs)
    self._at_bucket = self.bucket2

  @action(auto_prefix=True, description="按设定离心力和持续时间启动一次离心循环。")
  async def start_spin_cycle(self, g: float, duration: float) -> None:
    _unilab_logger.debug("[UNILAB] Centrifuge.start_spin_cycle() called")
    """Deprecated: use `spin` instead."""
    warnings.warn(
      "`start_spin_cycle` is deprecated and will be removed in a future version. Use `spin` instead.",
      DeprecationWarning,
    )
    await self.spin(g=g, duration=duration)

  @action(auto_prefix=True, description="按设定离心力和持续时间执行离心。")
  async def spin(self, g: float, duration: float, **backend_kwargs) -> None:
    _unilab_logger.debug("[UNILAB] Centrifuge.spin() called")
    """Starts a spin cycle.

    Args:
      g: The g-force to spin at.
      duration: The duration of the spin in seconds. Time at speed.
      acceleration: The acceleration as a fraction of maximum acceleration (0-1).
    """
    await self.backend.spin(
      g=g,
      duration=duration,
      **backend_kwargs,
    )
    self._at_bucket = None

  @property
  @action(auto_prefix=True, description="获取当前位于操作位置的转篮/吊篮。")
  def at_bucket(self) -> Optional[ResourceHolder]:
    _unilab_logger.debug("[UNILAB] Centrifuge.at_bucket() called")
    """None if not at a bucket or unknown, otherwise the resource representing the bucket."""
    return self._at_bucket

  @action(auto_prefix=True, description="导出设备的序列化信息。")
  def serialize(self) -> dict:
    _unilab_logger.debug("[UNILAB] Centrifuge.serialize() called")
    return {
      **Machine.serialize(self),
      **Resource.serialize(self),
      "buckets": [bucket.serialize() for bucket in [self.bucket1, self.bucket2]],
    }

  @classmethod
  @action(auto_prefix=True, description="从序列化信息恢复设备表示。")
  def deserialize(cls, data: dict, allow_marshal: bool = False):
    _unilab_logger.debug("[UNILAB] Centrifuge.deserialize() called")
    backend = CentrifugeBackend.deserialize(data["backend"])
    buckets = tuple(ResourceHolder.deserialize(bucket) for bucket in data["buckets"])
    assert len(buckets) == 2
    return cls(
      backend=backend,
      name=data["name"],
      size_x=data["size_x"],
      size_y=data["size_y"],
      size_z=data["size_z"],
      rotation=Rotation.deserialize(data["rotation"]),
      category=data["category"],
      model=data["model"],
      buckets=buckets,
    )
  def _loader_proxy(self):
    loader = getattr(self, "loader", None)
    if loader is not None:
      return loader
    return self.backend

  @action(auto_prefix=True, description="将样品装入离心机。")
  async def load(self) -> None:
    return await self._loader_proxy().load()

  @action(auto_prefix=True, description="将样品从离心机中取出。")
  async def unload(self) -> None:  # DOOR arg?
    return await self._loader_proxy().unload()


class Loader(Machine, ResourceHolder):
  """The front end for centrifuge loaders.
  Centrifuge loaders are devices that can load and unload samples from centrifuges."""

  def __init__(
    self,
    backend: LoaderBackend,
    centrifuge: Centrifuge,
    name: str,
    size_x: float,
    size_y: float,
    size_z: float,
    child_location: Coordinate,
    rotation=None,
    category="loader",
    model=None,
  ) -> None:
    Machine.__init__(self, backend=backend)
    ResourceHolder.__init__(
      self,
      name=name,
      size_x=size_x,
      size_y=size_y,
      size_z=size_z,
      child_location=child_location,
      rotation=rotation,
      category=category,
      model=model,
    )
    self.backend: LoaderBackend = backend  # fix type
    self.centrifuge = centrifuge

  async def load(self) -> None:
    if not self.centrifuge.door_open:
      raise CentrifugeDoorError("Centrifuge door must be open to load a plate.")

    if self.centrifuge.at_bucket is None:
      raise NotAtBucketError(
        "Centrifuge must be at a bucket to load a plate, but current position is unknown or not at "
        "a bucket. Use centrifuge.go_to_bucket{1,2}() to move to a bucket."
      )

    if self.resource is None:
      raise LoaderNoPlateError("Loader must have a plate to load.")

    if self.centrifuge.at_bucket.resource is not None:
      raise BucketHasPlateError("Bucket must be empty to load a plate.")

    await self.backend.load()

    self.centrifuge.at_bucket.assign_child_resource(self.resource, location=Coordinate.zero())

  async def unload(self) -> None:  # DOOR arg?
    if not self.centrifuge.door_open:
      raise CentrifugeDoorError("Centrifuge door must be open to unload a plate.")

    if self.centrifuge.at_bucket is None:
      raise NotAtBucketError(
        "Centrifuge must be at a bucket to unload a plate, but current position is unknown or not "
        "at a bucket. Use centrifuge.go_to_bucket{1,2}() to move to a bucket."
      )

    if self.centrifuge.at_bucket.resource is None:
      raise BucketNoPlateError("Bucket must have a plate to unload.")

    await self.backend.unload()

    self.assign_child_resource(self.centrifuge.at_bucket.resource)

  def serialize(self) -> dict:
    return {
      "resource": ResourceHolder.serialize(self),
      "machine": Machine.serialize(self),
      "centrifuge": self.centrifuge.serialize(),
    }

  @classmethod
  def deserialize(cls, data: dict, allow_marshal: bool = False):
    return cls(
      backend=LoaderBackend.deserialize(data["machine"]["backend"]),
      centrifuge=Centrifuge.deserialize(data["centrifuge"]),
      name=data["resource"]["name"],
      size_x=data["resource"]["size_x"],
      size_y=data["resource"]["size_y"],
      size_z=data["resource"]["size_z"],
      child_location=deserialize(data["resource"]["child_location"]),
      rotation=deserialize(data["resource"]["rotation"]),
      category=data["resource"]["category"],
      model=data["resource"]["model"],
    )
