"""
Auto-generated by Build Agent
Original: pylabrobot/plate_reading/plate_reader.py

[UNILAB DEBUG] 此驱动已注入调试日志
- 每个方法被调用时会打印日志
- 日志格式: [UNILAB] ClassName.method_name() called
- 查看日志: logging.getLogger("unilab.driver").setLevel(logging.DEBUG)
"""
from unilabos.registry.decorators import action, device
from typing import Dict, Any, Optional
import logging
import warnings as _warnings
_warnings.filterwarnings("ignore", message=r"pkg_resources is deprecated as an API\..*")
import sys as _sys
import types as _types

# 兼容性：部分上游框架（例如 lantz）在 import-time 强制加载 Qt（PyQt4/PySide1），
# 在 headless/现代 Python 环境中通常不存在这些绑定，会导致导入直接失败。
# 这里预注入一个最小的 `lantz.utils.qt` shim，避免触发其 Qt loader。
if "lantz.utils.qt" not in _sys.modules:
    _qt_mod = _types.ModuleType("lantz.utils.qt")

    class _DummyQtCore:
        class QObject:
            def __init__(self, *_args, **_kwargs):
                # 兼容 QObject(parent=...) 等调用
                return None

        @staticmethod
        def Signal(*_args, **_kwargs):
            return object()

        @staticmethod
        def Slot(*_args, **_kwargs):
            def _decorator(fn):
                return fn

            return _decorator

    _qt_mod.QtCore = _DummyQtCore

    class _DummySuperQObject(_DummyQtCore.QObject):
        def __new__(cls, *_args, **_kwargs):
            return super().__new__(cls)

        def __init__(self, *_args, **_kwargs):
            # 允许 Driver(...) 传参，不触发 object.__init__ 的 TypeError
            return None

    _qt_mod.MetaQObject = type
    _qt_mod.SuperQObject = _DummySuperQObject
    _sys.modules["lantz.utils.qt"] = _qt_mod

# Unilab 驱动调试日志
_unilab_logger = logging.getLogger("unilab.driver.PlateReader")
_unilab_logger.setLevel(logging.DEBUG)
if not _unilab_logger.handlers:
    _handler = logging.StreamHandler()
    _handler.setFormatter(logging.Formatter("[%(asctime)s] %(message)s"))
    _unilab_logger.addHandler(_handler)

# Vendored repo packages: pylabrobot, pylabrobot
import sys as _sys
from pathlib import Path as _Path
_vendor_root = _Path(__file__).resolve().parent / "_vendor"
if _vendor_root.exists() and str(_vendor_root) not in _sys.path:
    _sys.path.insert(0, str(_vendor_root))

import logging
from typing import Dict, List, Optional, cast

from pylabrobot.machines.machine import Machine, need_setup_finished
from pylabrobot.plate_reading.backend import PlateReaderBackend
from pylabrobot.plate_reading.standard import NoPlateError
from pylabrobot.resources import Coordinate, Plate, Resource, ResourceHolder, Well

logger = logging.getLogger(__name__)


@device(
  id="plate_reader",
  category=["Microplate Reader"],
  description="用于读取微孔板中各孔的吸光度、荧光和发光信号的实验仪器，常用于生化分析、细胞实验和板式检测流程。",
)
class PlateReader(ResourceHolder, Machine):
  """The front end for plate readers. Plate readers are devices that can read luminescence,
  absorbance, or fluorescence from a plate.

  Plate readers are asynchronous, meaning that their methods will return immediately and
  will not block.

  Here's an example of how to use this class in a Jupyter Notebook:

  >>> from pylabrobot.plate_reading.clario_star import CLARIOStarBackend
  >>> pr = PlateReader(backend=CLARIOStarBackend())
  >>> pr.setup()
  >>> await pr.read_luminescence()
  [[value1, value2, value3, ...], [value1, value2, value3, ...], ...
  """

  def __init__(
    self,
    name: str,
    size_x: float,
    size_y: float,
    size_z: float,
    backend: PlateReaderBackend,
    category: Optional[str] = "plate_reader",
    model: Optional[str] = None,
    child_location: Coordinate = Coordinate.zero(),
    preferred_pickup_location: Optional[Coordinate] = None,
  ) -> None:
    print("[UNILAB] PlateReader.__init__() called", flush=True)
    ResourceHolder.__init__(
      self,
      name=name,
      size_x=size_x,
      size_y=size_y,
      size_z=size_z,
      category=category,
      model=model,
      child_location=child_location,
      preferred_pickup_location=preferred_pickup_location,
    )
    Machine.__init__(self, backend=backend)
    self.backend: PlateReaderBackend = backend  # fix type

  @action(auto_prefix=True, description="将微孔板资源分配并装载到酶标仪中。")
  def assign_child_resource(
    self,
    resource: Resource,
    location: Optional[Coordinate] = None,
    reassign: bool = True,
  ):
    _unilab_logger.debug("[UNILAB] PlateReader.assign_child_resource() called")
    if len([c for c in self.children if isinstance(c, Plate)]) >= 1:
      raise ValueError("There already is a plate in the plate reader.")

    super().assign_child_resource(resource, location=location, reassign=reassign)

  @action(auto_prefix=True, description="获取当前装载的微孔板。")
  def get_plate(self) -> Plate:
    _unilab_logger.debug("[UNILAB] PlateReader.get_plate() called")
    plate_children = [c for c in self.children if isinstance(c, Plate)]
    if len(plate_children) == 0:
      raise NoPlateError("There is no plate in the plate reader.")
    return cast(Plate, plate_children[0])

  @need_setup_finished
  @action(auto_prefix=True, description="打开酶标仪的舱门或托盘，以便放入或取出微孔板。")
  async def open(self, **backend_kwargs) -> None:
    _unilab_logger.debug("[UNILAB] PlateReader.open() called")
    await self.backend.open(**backend_kwargs)

  @need_setup_finished
  @action(auto_prefix=True, description="关闭酶标仪的舱门或托盘，以准备检测。")
  async def close(self, **backend_kwargs) -> None:
    _unilab_logger.debug("[UNILAB] PlateReader.close() called")
    plate = self.get_plate() if len(self.children) > 0 else None
    await self.backend.close(plate=plate, **backend_kwargs)

  @need_setup_finished
  @action(auto_prefix=True, description="在指定焦高条件下读取微孔板各孔的发光信号。")
  async def read_luminescence(
    self,
    focal_height: float,
    wells: Optional[List[Well]] = None,
    use_new_return_type: bool = False,
    **backend_kwargs,
  ) -> List[Dict]:
    _unilab_logger.debug("[UNILAB] PlateReader.read_luminescence() called")
    """Read the luminescence from the plate reader.

    Args:
      focal_height: The focal height to read the luminescence at, in micrometers.
      use_new_return_type: Whether to return the new return type, which is a list of dictionaries.

    Returns:
      A list of dictionaries, one for each measurement. Each dictionary contains:
        "time": float,
        "temperature": float,
        "data": List[List[float]]
    """

    result = await self.backend.read_luminescence(
      plate=self.get_plate(),
      wells=wells or self.get_plate().get_all_items(),
      focal_height=focal_height,
      **backend_kwargs,
    )

    if not use_new_return_type:
      logger.warning(
        "The return type of read_luminescence will change in a future version. Please set "
        "use_new_return_type=True to use the new return type."
      )
      return result[0]["data"]  # type: ignore[no-any-return]
    return result

  @need_setup_finished
  @action(auto_prefix=True, description="在指定波长下读取微孔板各孔的吸光度。")
  async def read_absorbance(
    self,
    wavelength: int,
    wells: Optional[List[Well]] = None,
    use_new_return_type: bool = False,
    **backend_kwargs,
  ) -> List[Dict]:
    _unilab_logger.debug("[UNILAB] PlateReader.read_absorbance() called")
    """Read the absorbance from the plate reader.

    Args:
      wavelength: The wavelength to read the absorbance at, in nanometers.
      use_new_return_type: Whether to return the new return type, which is a list of dictionaries.

    Returns:
      A list of dictionaries, one for each measurement. Each dictionary contains:
        "wavelength": int,
        "time": float,
        "temperature": float,
        "data": List[List[float]]
    """

    result = await self.backend.read_absorbance(
      plate=self.get_plate(),
      wells=wells or self.get_plate().get_all_items(),
      wavelength=wavelength,
      **backend_kwargs,
    )

    if not use_new_return_type:
      logger.warning(
        "The return type of read_absorbance will change in a future version. Please set "
        "use_new_return_type=True to use the new return type."
      )
      return result[0]["data"]  # type: ignore[no-any-return]
    return result

  @need_setup_finished
  @action(auto_prefix=True, description="在指定激发波长、发射波长和焦高条件下读取微孔板各孔的荧光信号。")
  async def read_fluorescence(
    self,
    excitation_wavelength: int,
    emission_wavelength: int,
    focal_height: float,
    wells: Optional[List[Well]] = None,
    use_new_return_type: bool = False,
    **backend_kwargs,
  ) -> List[Dict]:
    _unilab_logger.debug("[UNILAB] PlateReader.read_fluorescence() called")
    """Read the fluorescence from the plate reader.

    Args:
      excitation_wavelength: The excitation wavelength to read the fluorescence at, in nanometers.
      emission_wavelength: The emission wavelength to read the fluorescence at, in nanometers.
      focal_height: The focal height to read the fluorescence at, in micrometers.
      use_new_return_type: Whether to return the new return type, which is a list of dictionaries.

    Returns:
      A list of dictionaries, one for each measurement. Each dictionary contains:
        "ex_wavelength": int,
        "em_wavelength": int,
        "time": float,
        "temperature": float,
        "data": List[List[float]]
    """

    if excitation_wavelength > emission_wavelength:
      logger.warning(
        "Excitation wavelength is greater than emission wavelength. This is unusual and may indicate an error."
      )

    result = await self.backend.read_fluorescence(
      plate=self.get_plate(),
      wells=wells or self.get_plate().get_all_items(),
      excitation_wavelength=excitation_wavelength,
      emission_wavelength=emission_wavelength,
      focal_height=focal_height,
      **backend_kwargs,
    )
    if not use_new_return_type:
      logger.warning(
        "The return type of read_fluorescence will change in a future version. Please set "
        "use_new_return_type=True to use the new return type."
      )
      return result[0]["data"]  # type: ignore[no-any-return]
    return result

  @action(auto_prefix=True, description="序列化酶标仪的当前状态或资源信息。")
  def serialize(self) -> dict:
    _unilab_logger.debug("[UNILAB] PlateReader.serialize() called")
    return {**Resource.serialize(self), **Machine.serialize(self)}
