"""
Auto-generated by Build Agent
Original: pylabrobot/sealing/sealer.py

[UNILAB DEBUG] 此驱动已注入调试日志
- 每个方法被调用时会打印日志
- 日志格式: [UNILAB] ClassName.method_name() called
- 查看日志: logging.getLogger("unilab.driver").setLevel(logging.DEBUG)
"""
from unilabos.registry.decorators import action, device
from typing import Dict, Any, Optional
import logging
import warnings as _warnings
_warnings.filterwarnings("ignore", message=r"pkg_resources is deprecated as an API\..*")
import sys as _sys
import types as _types

# 兼容性：部分上游框架（例如 lantz）在 import-time 强制加载 Qt（PyQt4/PySide1），
# 在 headless/现代 Python 环境中通常不存在这些绑定，会导致导入直接失败。
# 这里预注入一个最小的 `lantz.utils.qt` shim，避免触发其 Qt loader。
if "lantz.utils.qt" not in _sys.modules:
    _qt_mod = _types.ModuleType("lantz.utils.qt")

    class _DummyQtCore:
        class QObject:
            def __init__(self, *_args, **_kwargs):
                # 兼容 QObject(parent=...) 等调用
                return None

        @staticmethod
        def Signal(*_args, **_kwargs):
            return object()

        @staticmethod
        def Slot(*_args, **_kwargs):
            def _decorator(fn):
                return fn

            return _decorator

    _qt_mod.QtCore = _DummyQtCore

    class _DummySuperQObject(_DummyQtCore.QObject):
        def __new__(cls, *_args, **_kwargs):
            return super().__new__(cls)

        def __init__(self, *_args, **_kwargs):
            # 允许 Driver(...) 传参，不触发 object.__init__ 的 TypeError
            return None

    _qt_mod.MetaQObject = type
    _qt_mod.SuperQObject = _DummySuperQObject
    _sys.modules["lantz.utils.qt"] = _qt_mod

# Unilab 驱动调试日志
_unilab_logger = logging.getLogger("unilab.driver.Sealer")
_unilab_logger.setLevel(logging.DEBUG)
if not _unilab_logger.handlers:
    _handler = logging.StreamHandler()
    _handler.setFormatter(logging.Formatter("[%(asctime)s] %(message)s"))
    _unilab_logger.addHandler(_handler)

# Vendored repo packages: pylabrobot, pylabrobot
import sys as _sys
from pathlib import Path as _Path
_vendor_root = _Path(__file__).resolve().parent / "_vendor"
if _vendor_root.exists() and str(_vendor_root) not in _sys.path:
    _sys.path.insert(0, str(_vendor_root))

from pylabrobot.machines import Machine

from pylabrobot.sealing.backend import SealerBackend


@device(
  id="sealer",
  category=["Plate Sealer"],
  description="用于实验室自动化中对微孔板进行封膜的设备，可执行封膜、开合机构控制，以及温度设置与读取。",
)
class Sealer(Machine):
  """A microplate sealer"""

  def __init__(self, backend: SealerBackend):
    print("[UNILAB] Sealer.__init__() called", flush=True)
    super().__init__(backend=backend)
    self.backend: SealerBackend = backend  # fix type

  @action(auto_prefix=True, description="按设定温度和持续时间执行微孔板封膜。")
  async def seal(self, temperature: int, duration: float):
    _unilab_logger.debug("[UNILAB] Sealer.seal() called")
    return await self.backend.seal(temperature=temperature, duration=duration)

  @action(auto_prefix=True, description="打开封膜机机构。")
  async def open(self):
    _unilab_logger.debug("[UNILAB] Sealer.open() called")
    return await self.backend.open()

  @action(auto_prefix=True, description="关闭封膜机机构。")
  async def close(self):
    _unilab_logger.debug("[UNILAB] Sealer.close() called")
    return await self.backend.close()

  @action(auto_prefix=True, description="设置封膜机温度。")
  async def set_temperature(self, temperature: float):
    _unilab_logger.debug("[UNILAB] Sealer.set_temperature() called")
    """Set the temperature of the sealer in degrees Celsius."""
    return await self.backend.set_temperature(temperature=temperature)

  @action(auto_prefix=True, description="获取封膜机温度。")
  async def get_temperature(self) -> float:
    _unilab_logger.debug("[UNILAB] Sealer.get_temperature() called")
    """Get the current temperature of the sealer in degrees Celsius."""
    return await self.backend.get_temperature()
