"""
Auto-generated by Build Agent
Original: pylabrobot/storage/incubator.py

[UNILAB DEBUG] 此驱动已注入调试日志
- 每个方法被调用时会打印日志
- 日志格式: [UNILAB] ClassName.method_name() called
- 查看日志: logging.getLogger("unilab.driver").setLevel(logging.DEBUG)
"""
from unilabos.registry.decorators import action, device
from typing import Dict, Any, Optional
import logging
import warnings as _warnings
_warnings.filterwarnings("ignore", message=r"pkg_resources is deprecated as an API\..*")
import sys as _sys
import types as _types

# 兼容性：部分上游框架（例如 lantz）在 import-time 强制加载 Qt（PyQt4/PySide1），
# 在 headless/现代 Python 环境中通常不存在这些绑定，会导致导入直接失败。
# 这里预注入一个最小的 `lantz.utils.qt` shim，避免触发其 Qt loader。
if "lantz.utils.qt" not in _sys.modules:
    _qt_mod = _types.ModuleType("lantz.utils.qt")

    class _DummyQtCore:
        class QObject:
            def __init__(self, *_args, **_kwargs):
                # 兼容 QObject(parent=...) 等调用
                return None

        @staticmethod
        def Signal(*_args, **_kwargs):
            return object()

        @staticmethod
        def Slot(*_args, **_kwargs):
            def _decorator(fn):
                return fn

            return _decorator

    _qt_mod.QtCore = _DummyQtCore

    class _DummySuperQObject(_DummyQtCore.QObject):
        def __new__(cls, *_args, **_kwargs):
            return super().__new__(cls)

        def __init__(self, *_args, **_kwargs):
            # 允许 Driver(...) 传参，不触发 object.__init__ 的 TypeError
            return None

    _qt_mod.MetaQObject = type
    _qt_mod.SuperQObject = _DummySuperQObject
    _sys.modules["lantz.utils.qt"] = _qt_mod

# Unilab 驱动调试日志
_unilab_logger = logging.getLogger("unilab.driver.Incubator")
_unilab_logger.setLevel(logging.DEBUG)
if not _unilab_logger.handlers:
    _handler = logging.StreamHandler()
    _handler.setFormatter(logging.Formatter("[%(asctime)s] %(message)s"))
    _unilab_logger.addHandler(_handler)

# Vendored repo packages: pylabrobot, pylabrobot
import sys as _sys
from pathlib import Path as _Path
_vendor_root = _Path(__file__).resolve().parent / "_vendor"
if _vendor_root.exists() and str(_vendor_root) not in _sys.path:
    _sys.path.insert(0, str(_vendor_root))

import random
from typing import List, Literal, Optional, Union, cast

from pylabrobot.machines import Machine
from pylabrobot.resources import (
  Coordinate,
  Plate,
  PlateCarrier,
  PlateHolder,
  Resource,
  ResourceNotFoundError,
  Rotation,
)
from pylabrobot.serializer import deserialize, serialize

from pylabrobot.storage.backend import IncubatorBackend


class NoFreeSiteError(Exception):
  pass


@device(
  id="incubator",
  category=["Automated Microplate Incubator Storage System"],
  description="一种用于存放并温控培养微孔板或培养板的自动化实验室培养箱，通常具有多个板位、装载托盘和可开闭门机构，可在设定温度下进行样品孵育，并支持板件取放与振荡混匀。常用于细胞培养、酶反应、样品保温和自动化流程中的板式孵育步骤。",
)
class Incubator(Machine, Resource):
  def __init__(
    self,
    backend: IncubatorBackend,
    name: str,
    size_x: float,
    size_y: float,
    size_z: float,
    racks: List[PlateCarrier],
    loading_tray_location: Coordinate,
    rotation: Optional[Rotation] = None,
    category: Optional[str] = None,
    model: Optional[str] = None,
  ):
    print("[UNILAB] Incubator.__init__() called", flush=True)
    Machine.__init__(self, backend=backend)
    self.backend: IncubatorBackend = backend  # fix type
    Resource.__init__(
      self,
      name=name,
      size_x=size_x,
      size_y=size_y,
      size_z=size_z,
      rotation=rotation,
      category=category,
      model=model,
    )
    self.loading_tray = PlateHolder(
      name=self.name + "_tray", size_x=127.76, size_y=85.48, size_z=0, pedestal_size_z=0
    )
    self.assign_child_resource(self.loading_tray, location=loading_tray_location)

    self._racks = racks
    for rack in self._racks:
      self.assign_child_resource(rack, location=None)

  @property
  @action(auto_prefix=True, description="列出培养箱内的板架或板位信息")
  def racks(self) -> List[PlateCarrier]:
    _unilab_logger.debug("[UNILAB] Incubator.racks() called")
    return self._racks

  async def setup(self, **backend_kwargs):
    _unilab_logger.debug("[UNILAB] Incubator.setup() called")
    await super().setup()
    await self.backend.set_racks(self._racks)

  @action(auto_prefix=True, description="获取空闲板位数量")
  def get_num_free_sites(self) -> int:
    _unilab_logger.debug("[UNILAB] Incubator.get_num_free_sites() called")
    return sum(len(rack.get_free_sites()) for rack in self._racks)

  @action(auto_prefix=True, description="根据板名查找所在板位")
  def get_site_by_plate_name(self, plate_name: str) -> PlateHolder:
    _unilab_logger.debug("[UNILAB] Incubator.get_site_by_plate_name() called")
    for rack in self._racks:
      for site in rack.sites.values():
        if site.resource is not None and site.resource.name == plate_name:
          return site
    raise ResourceNotFoundError(f"Plate {plate_name} not found in incubator '{self.name}'")

  @action(auto_prefix=True, description="将指定培养板从培养箱取到装载托盘")
  async def fetch_plate_to_loading_tray(self, plate_name: str) -> Plate:
    _unilab_logger.debug("[UNILAB] Incubator.fetch_plate_to_loading_tray() called")
    """Fetch a plate from the incubator and put it on the loading tray."""

    site = self.get_site_by_plate_name(plate_name)
    plate = site.resource
    assert plate is not None
    await self.backend.fetch_plate_to_loading_tray(plate)
    plate.unassign()
    self.loading_tray.assign_child_resource(plate)
    return plate

  def _find_available_sites_sorted(self, plate: Plate) -> List[PlateHolder]:
    _unilab_logger.debug("[UNILAB] Incubator._find_available_sites_sorted() called")
    """Find all sites that are free and fit the plate, sorted by size."""

    def _plate_height(p: Plate):
      _unilab_logger.debug("[UNILAB] Incubator._plate_height() called")
      if p.has_lid():
        # TODO: we can use plr nesting height
        # lid.location.z + lid.get_anchor(z="t").z
        return p.get_size_z() + 3
      return p.get_size_z()

    available = [
      site
      for rack in self._racks
      for site in rack.get_free_sites()
      if site.get_size_z() >= _plate_height(plate)
    ]
    if len(available) == 0:
      raise NoFreeSiteError(
        f"No free site found in incubator '{self.name}' for plate '{plate.name}'"
      )
    return sorted(available, key=lambda site: site.get_size_z())

  @action(auto_prefix=True, description="查找可容纳该培养板的最小合适板位")
  def find_smallest_site_for_plate(self, plate: Plate) -> PlateHolder:
    _unilab_logger.debug("[UNILAB] Incubator.find_smallest_site_for_plate() called")
    return self._find_available_sites_sorted(plate)[0]

  @action(auto_prefix=True, description="随机查找一个可用板位")
  def find_random_site(self, plate: Plate) -> PlateHolder:
    _unilab_logger.debug("[UNILAB] Incubator.find_random_site() called")
    return random.choice(self._find_available_sites_sorted(plate))

  @action(auto_prefix=True, description="将装载托盘上的培养板放入培养箱指定板位")
  async def take_in_plate(self, site: Union[PlateHolder, Literal["random", "smallest"]]):
    _unilab_logger.debug("[UNILAB] Incubator.take_in_plate() called")
    """Take a plate from the loading tray and put it in the incubator."""

    plate = cast(Plate, self.loading_tray.resource)
    if plate is None:
      raise ResourceNotFoundError(f"No plate on the loading tray of incubator '{self.name}'")

    if site == "random":
      site = self.find_random_site(plate)
    elif site == "smallest":
      site = self.find_smallest_site_for_plate(plate)
    elif isinstance(site, PlateHolder):
      if site not in self._find_available_sites_sorted(plate):
        raise ValueError(f"Site {site.name} is not available for plate {plate.name}")
    else:
      raise ValueError(f"Invalid site: {site}")
    await self.backend.take_in_plate(plate, site)
    plate.unassign()
    site.assign_child_resource(plate)

  @action(auto_prefix=True, description="设置培养箱温度")
  async def set_temperature(self, temperature: float):
    _unilab_logger.debug("[UNILAB] Incubator.set_temperature() called")
    """Set the temperature of the incubator in degrees Celsius."""
    return await self.backend.set_temperature(temperature)

  @action(auto_prefix=True, description="获取培养箱温度")
  async def get_temperature(self) -> float:
    _unilab_logger.debug("[UNILAB] Incubator.get_temperature() called")
    return await self.backend.get_temperature()

  @action(auto_prefix=True, description="打开培养箱门")
  async def open_door(self):
    _unilab_logger.debug("[UNILAB] Incubator.open_door() called")
    return await self.backend.open_door()

  @action(auto_prefix=True, description="关闭培养箱门")
  async def close_door(self):
    _unilab_logger.debug("[UNILAB] Incubator.close_door() called")
    return await self.backend.close_door()

  @action(auto_prefix=True, description="以设定频率开始振荡")
  async def start_shaking(self, frequency: float = 1.0):
    _unilab_logger.debug("[UNILAB] Incubator.start_shaking() called")
    await self.backend.start_shaking(frequency=frequency)

  @action(auto_prefix=True, description="停止振荡")
  async def stop_shaking(self):
    _unilab_logger.debug("[UNILAB] Incubator.stop_shaking() called")
    await self.backend.stop_shaking()

  @action(auto_prefix=True, description="汇总培养箱当前状态与板位占用情况")
  def summary(self) -> str:
    _unilab_logger.debug("[UNILAB] Incubator.summary() called")
    def create_pretty_table(header, *columns) -> str:
      _unilab_logger.debug("[UNILAB] Incubator.create_pretty_table() called")
      col_widths = [
        max(len(str(item)) for item in [header[i]] + list(columns[i])) for i in range(len(header))
      ]

      def format_row(row, border="|") -> str:
        _unilab_logger.debug("[UNILAB] Incubator.format_row() called")
        return (
          f"{border} "
          + " | ".join(f"{str(row[i]).ljust(col_widths[i])}" for i in range(len(row)))
          + f" {border}"
        )

      def separator_line(cross: str = "+", line: str = "-") -> str:
        _unilab_logger.debug("[UNILAB] Incubator.separator_line() called")
        return cross + cross.join(line * (width + 2) for width in col_widths) + cross

      table = []
      table.append(separator_line())  # Top border
      table.append(format_row(header))
      table.append(separator_line())  # Header separator
      for row in zip(*columns):
        table.append(format_row(row))
      table.append(separator_line())  # Bottom border
      return "\n".join(table)

    header = [f"Rack {i}" for i in range(len(self._racks))]
    sites = [
      [site.resource.name if site.resource else "<empty>" for site in reversed(rack.sites.values())]
      for rack in self._racks
    ]
    return create_pretty_table(header, *sites)

  @action(auto_prefix=True, description="导出培养箱配置或当前布局信息")
  def serialize(self):
    _unilab_logger.debug("[UNILAB] Incubator.serialize() called")
    return {
      **Machine.serialize(self),
      **Resource.serialize(self),
      "backend": self.backend.serialize(),
      "racks": [rack.serialize() for rack in self._racks],
      "loading_tray_location": serialize(self.loading_tray.location),
    }

  @classmethod
  @action(auto_prefix=True, description="从已保存数据恢复培养箱配置或布局")
  def deserialize(cls, data: dict, allow_marshal: bool = False):
    _unilab_logger.debug("[UNILAB] Incubator.deserialize() called")
    backend = IncubatorBackend.deserialize(data.pop("backend"))
    return cls(
      backend=backend,
      name=data["name"],
      size_x=data["size_x"],
      size_y=data["size_y"],
      size_z=data["size_z"],
      racks=[PlateCarrier.deserialize(rack) for rack in data["racks"]],
      loading_tray_location=cast(Coordinate, deserialize(data["loading_tray_location"])),
      rotation=Rotation.deserialize(data["rotation"]),
      category=data["category"],
      model=data["model"],
    )
