"""
Auto-generated by Build Agent
Original: pylabrobot/storage/inheco/incubator_shaker.py

[UNILAB DEBUG] 此驱动已注入调试日志
- 每个方法被调用时会打印日志
- 日志格式: [UNILAB] ClassName.method_name() called
- 查看日志: logging.getLogger("unilab.driver").setLevel(logging.DEBUG)
"""
from unilabos.registry.decorators import action, device
from typing import Dict, Any, Optional
import logging
import warnings as _warnings
_warnings.filterwarnings("ignore", message=r"pkg_resources is deprecated as an API\..*")
import sys as _sys
import types as _types

# 兼容性：部分上游框架（例如 lantz）在 import-time 强制加载 Qt（PyQt4/PySide1），
# 在 headless/现代 Python 环境中通常不存在这些绑定，会导致导入直接失败。
# 这里预注入一个最小的 `lantz.utils.qt` shim，避免触发其 Qt loader。
if "lantz.utils.qt" not in _sys.modules:
    _qt_mod = _types.ModuleType("lantz.utils.qt")

    class _DummyQtCore:
        class QObject:
            def __init__(self, *_args, **_kwargs):
                # 兼容 QObject(parent=...) 等调用
                return None

        @staticmethod
        def Signal(*_args, **_kwargs):
            return object()

        @staticmethod
        def Slot(*_args, **_kwargs):
            def _decorator(fn):
                return fn

            return _decorator

    _qt_mod.QtCore = _DummyQtCore

    class _DummySuperQObject(_DummyQtCore.QObject):
        def __new__(cls, *_args, **_kwargs):
            return super().__new__(cls)

        def __init__(self, *_args, **_kwargs):
            # 允许 Driver(...) 传参，不触发 object.__init__ 的 TypeError
            return None

    _qt_mod.MetaQObject = type
    _qt_mod.SuperQObject = _DummySuperQObject
    _sys.modules["lantz.utils.qt"] = _qt_mod

# Unilab 驱动调试日志
_unilab_logger = logging.getLogger("unilab.driver.IncubatorShakerStack")
_unilab_logger.setLevel(logging.DEBUG)
if not _unilab_logger.handlers:
    _handler = logging.StreamHandler()
    _handler.setFormatter(logging.Formatter("[%(asctime)s] %(message)s"))
    _unilab_logger.addHandler(_handler)

# Vendored repo packages: pylabrobot, pylabrobot
import sys as _sys
from pathlib import Path as _Path
_vendor_root = _Path(__file__).resolve().parent / "_vendor"
if _vendor_root.exists() and str(_vendor_root) not in _sys.path:
    _sys.path.insert(0, str(_vendor_root))

from typing import Dict

from pylabrobot.machines.machine import Machine
from pylabrobot.resources import Coordinate, Resource, ResourceHolder

from pylabrobot.storage.inheco.incubator_shaker_backend import InhecoIncubatorShakerStackBackend, InhecoIncubatorShakerUnit


@device(
  id="incubator_shaker_stack",
  category=["Microplate Thermoshaker"],
  description="由多个可堆叠孵育振荡单元组成的实验室自动化设备，带有装载托盘，可对样品或微孔板进行温度控制孵育与振荡混匀，常用于自动化培养、反应孵育和样品处理流程。",
)
class IncubatorShakerStack(Resource, Machine):
  """Frontend for a stack of INHECO Incubator/Shaker units.

  - Combines Carrier (geometric resource) and Machine (device lifecycle).
  - Owns a backend instance for serial communication.
  - Handles sequential (not concurrent) setup/teardown across all units.
  """

  def __init__(self, backend: InhecoIncubatorShakerStackBackend):
    print("[UNILAB] IncubatorShakerStack.__init__() called", flush=True)
    Resource.__init__(
      self,
      name="inheco_incubator_shaker_stack",
      size_x=149.0,
      size_y=268.5,
      size_z=58.0,  # MP: 58, Shaker MP: 88.5, DWP: 104, Shaker DWP: 139 mm
      category="incubator_shaker_stack",
    )

    Machine.__init__(self, backend=backend)
    self.backend: InhecoIncubatorShakerStackBackend = backend
    self.units: list[InhecoIncubatorShakerUnit] = []
    self.loading_trays: list[ResourceHolder] = []

  @property
  @action(auto_prefix=True, description="获取堆叠中已连接单元的数量。")
  def num_units(self) -> int:
    _unilab_logger.debug("[UNILAB] IncubatorShakerStack.num_units() called")
    """Return number of connected units in the stack."""
    return len(self.units)

  # ------------------------------------------------------------------------
  # Lifecycle & Resource setup
  # ------------------------------------------------------------------------

  _incubator_size_z_dict = {
    "incubator_mp": 58.0,
    "incubator_shaker_mp": 88.5,
    "incubator_dwp": 104,
    "incubator_shaker_dwp": 139,
  }
  _incubator_loading_tray_location = {  # TODO: rough measurements, verify
    "incubator_mp": None,  # TODO: add when available
    "incubator_shaker_mp": Coordinate(x=30.5, y=-150.5, z=51.2),
    "incubator_dwp": None,  # TODO: add when available
    "incubator_shaker_dwp": Coordinate(x=30.5, y=-150.5, z=51.2),
  }

  _possible_tray_y_coordinates = {
    "open": -150.5,  # TODO: verify by careful testing in controlled geometry setup
    "closed": +24.0,
  }

  _chamber_z_clearance = 2

  _acceptable_plate_z_dimensions = {
    "incubator_mp": 18 - _chamber_z_clearance,
    "incubator_shaker_mp": 50 - _chamber_z_clearance,
    "incubator_dwp": 18 - _chamber_z_clearance,
    "incubator_shaker_dwp": 53 - _chamber_z_clearance,
  }

  _incubator_power_credits_per_type = {
    "incubator_mp": 1.0,
    "incubator_dwp": 1.25,
    "incubator_shaker_mp": 1.6,
    "incubator_shaker_dwp": 2.5,
  }

  async def setup(self, **backend_kwargs) -> None:
    _unilab_logger.debug("[UNILAB] IncubatorShakerStack.setup() called")
    """Connect to the stack and build per-unit proxies."""

    await self.backend.setup(**backend_kwargs)

    self.power_credit = 0.0

    # Calculate true stack size
    stack_size_z = 0.0

    for i in range(self.backend.number_of_connected_units):
      # Create unit proxies
      unit = InhecoIncubatorShakerUnit(self.backend, index=i)
      self.units.append(unit)

      # Create loading tray resources and calculate their locations
      unit_type = self.backend.unit_composition[i]
      self.power_credit += self._incubator_power_credits_per_type[unit_type]
      unit_size_z = self._incubator_size_z_dict[unit_type]

      loading_tray = ResourceHolder(
        size_x=127.76, size_y=85.48, size_z=0, name=f"unit-{i}-loading-tray"
      )
      self.loading_trays.append(loading_tray)

      loc = self._incubator_loading_tray_location[unit_type]
      if loc is None:
        raise ValueError(
          f"Loading tray location for unit type {unit_type} is not defined. " "Cannot set up stack."
        )

      self.assign_child_resource(
        loading_tray,
        location=Coordinate(
          x=loc.x,
          y=self._possible_tray_y_coordinates[
            "closed"
          ],  # setup finishes with all loading trays closed
          z=stack_size_z + loc.z,
        ),
      )
      stack_size_z += unit_size_z

    self._size_z = stack_size_z

    assert (
      self.power_credit < 5
    ), f"Too many units: unit composition {self.backend.unit_composition} is exceeding 5 power credit limit. Reduce number of units."

  async def stop(self):
    _unilab_logger.debug("[UNILAB] IncubatorShakerStack.stop() called")
    """Gracefully stop backend communication."""
    await self.backend.stop()

  @action(auto_prefix=True, description="查询所有单元的装载托盘状态。")
  async def request_loading_tray_states(self) -> dict:
    _unilab_logger.debug("[UNILAB] IncubatorShakerStack.request_loading_tray_states() called")
    """Request loading tray states for all units."""

    return {
      unit_index: await self.backend.request_drawer_status(stack_index=unit_index)
      for unit_index in range(self.num_units)
    }

  @action(auto_prefix=True, description="查询所有单元的温度控制状态。")
  async def request_temperature_control_states(self) -> dict:
    _unilab_logger.debug("[UNILAB] IncubatorShakerStack.request_temperature_control_states() called")
    """Request temperature control states for all units."""

    return {
      unit_index: await self.backend.is_temperature_control_enabled(stack_index=unit_index)
      for unit_index in range(self.num_units)
    }

  @action(auto_prefix=True, description="查询所有单元的振荡状态。")
  async def request_shaking_states(self) -> dict:
    _unilab_logger.debug("[UNILAB] IncubatorShakerStack.request_shaking_states() called")
    """Request shaking states for all units."""

    return {
      unit_index: await self.backend.is_shaking_enabled(stack_index=unit_index)
      for unit_index in range(self.num_units)
    }

  # ------------------------------------------------------------------------
  # Stack to unit master commands
  # ------------------------------------------------------------------------

  @action(auto_prefix=True, description="打开堆叠中的所有单元。")
  async def open_all(self) -> None:
    _unilab_logger.debug("[UNILAB] IncubatorShakerStack.open_all() called")
    """Open all units in the stack."""
    for i in range(self.num_units):
      await self.units[i].open()

  @action(auto_prefix=True, description="关闭堆叠中的所有单元。")
  async def close_all(self) -> None:
    _unilab_logger.debug("[UNILAB] IncubatorShakerStack.close_all() called")
    """Close all units in the stack."""
    for i in range(self.num_units):
      await self.units[i].close()

  @action(auto_prefix=True, description="启动所有单元的温度控制并设定目标温度。")
  async def start_all_temperature_control(self, target_temperature: float) -> None:
    _unilab_logger.debug("[UNILAB] IncubatorShakerStack.start_all_temperature_control() called")
    """Start temperature control for all units in the stack."""
    for i in range(self.num_units):
      await self.units[i].start_temperature_control(target_temperature)

  @action(auto_prefix=True, description="获取所有单元的当前温度。")
  async def get_all_temperatures(self) -> Dict[int, float]:
    _unilab_logger.debug("[UNILAB] IncubatorShakerStack.get_all_temperatures() called")
    """Get current temperature for all units in the stack."""
    temperatures = {}
    for i in range(self.num_units):
      temp = await self.units[i].get_temperature()
      temperatures[i] = temp
    return temperatures

  @action(auto_prefix=True, description="停止所有单元的温度控制。")
  async def stop_all_temperature_control(self) -> None:
    _unilab_logger.debug("[UNILAB] IncubatorShakerStack.stop_all_temperature_control() called")
    """Stop temperature control for all units in the stack."""
    for i in range(self.num_units):
      await self.units[i].stop_temperature_control()

  @action(auto_prefix=True, description="启动所有单元的振荡。")
  async def shake(self, *args, **kwargs) -> None:
    _unilab_logger.debug("[UNILAB] IncubatorShakerStack.shake() called")
    """Start shaking for all units in the stack."""
    for i in range(self.num_units):
      await self.units[i].shake(*args, **kwargs)

  @action(auto_prefix=True, description="停止所有单元的振荡。")
  async def stop_all_shaking(self) -> None:
    _unilab_logger.debug("[UNILAB] IncubatorShakerStack.stop_all_shaking() called")
    """Stop shaking for all units in the stack."""
    for i in range(self.num_units):
      await self.units[i].stop_shaking()

  # ------------------------------------------------------------------------
  # Unit accessors
  # ------------------------------------------------------------------------

  def __getitem__(self, index: int) -> InhecoIncubatorShakerUnit:
    _unilab_logger.debug("[UNILAB] IncubatorShakerStack.__getitem__() called")
    """Access a unit proxy via stack[index]."""
    return self.units[index]

  def __len__(self):
    _unilab_logger.debug("[UNILAB] IncubatorShakerStack.__len__() called")
    """Return number of connected units."""
    return len(self.units)
