"""
Auto-generated by Build Agent
Original: pylabrobot/storage/cytomat/cytomat.py

[UNILAB DEBUG] 此驱动已注入调试日志
- 每个方法被调用时会打印日志
- 日志格式: [UNILAB] ClassName.method_name() called
- 查看日志: logging.getLogger("unilab.driver").setLevel(logging.DEBUG)
"""
from unilabos.registry.decorators import action, device
from typing import Dict, Any, Optional
import logging
import warnings as _warnings
_warnings.filterwarnings("ignore", message=r"pkg_resources is deprecated as an API\..*")
import sys as _sys
import types as _types

# 兼容性：部分上游框架（例如 lantz）在 import-time 强制加载 Qt（PyQt4/PySide1），
# 在 headless/现代 Python 环境中通常不存在这些绑定，会导致导入直接失败。
# 这里预注入一个最小的 `lantz.utils.qt` shim，避免触发其 Qt loader。
if "lantz.utils.qt" not in _sys.modules:
    _qt_mod = _types.ModuleType("lantz.utils.qt")

    class _DummyQtCore:
        class QObject:
            def __init__(self, *_args, **_kwargs):
                # 兼容 QObject(parent=...) 等调用
                return None

        @staticmethod
        def Signal(*_args, **_kwargs):
            return object()

        @staticmethod
        def Slot(*_args, **_kwargs):
            def _decorator(fn):
                return fn

            return _decorator

    _qt_mod.QtCore = _DummyQtCore

    class _DummySuperQObject(_DummyQtCore.QObject):
        def __new__(cls, *_args, **_kwargs):
            return super().__new__(cls)

        def __init__(self, *_args, **_kwargs):
            # 允许 Driver(...) 传参，不触发 object.__init__ 的 TypeError
            return None

    _qt_mod.MetaQObject = type
    _qt_mod.SuperQObject = _DummySuperQObject
    _sys.modules["lantz.utils.qt"] = _qt_mod

# Unilab 驱动调试日志
_unilab_logger = logging.getLogger("unilab.driver.CytomatBackend")
_unilab_logger.setLevel(logging.DEBUG)
if not _unilab_logger.handlers:
    _handler = logging.StreamHandler()
    _handler.setFormatter(logging.Formatter("[%(asctime)s] %(message)s"))
    _unilab_logger.addHandler(_handler)

# Vendored repo packages: pylabrobot, pylabrobot
import sys as _sys
from pathlib import Path as _Path
_vendor_root = _Path(__file__).resolve().parent / "_vendor"
if _vendor_root.exists() and str(_vendor_root) not in _sys.path:
    _sys.path.insert(0, str(_vendor_root))

import asyncio
import logging
import time
import warnings
from typing import List, Literal, Optional, Union, cast

import serial

from pylabrobot.io.serial import Serial
from pylabrobot.resources import Plate, PlateCarrier, PlateHolder
from pylabrobot.storage.backend import IncubatorBackend
from pylabrobot.storage.cytomat.constants import (
  ActionRegister,
  ActionType,
  CytomatActionResponse,
  CytomatIncupationResponse,
  CytomatType,
  ErrorRegister,
  LoadStatusAtProcessor,
  LoadStatusFrontOfGate,
  SensorRegister,
  SwapStationPosition,
  WarningRegister,
)
from pylabrobot.storage.cytomat.errors import (
  CytomatBusyError,
  CytomatCommandUnknownError,
  CytomatTelegramStructureError,
  error_map,
  error_register_map,
)
from pylabrobot.storage.cytomat.schemas import (
  ActionRegisterState,
  OverviewRegisterState,
  SensorStates,
  SwapStationState,
)
from pylabrobot.storage.cytomat.utils import (
  hex_to_base_twelve,
  hex_to_binary,
  validate_storage_location_number,
)

logger = logging.getLogger(__name__)


@device(
  id="cytomat_backend",
  category=["Tissue Culture Chamber", "Automated Microplate Incubator Storage System"],
  description="这是一种用于微孔板自动存取、培养和转运的实验室培养存储设备，带有内部存储位、传送位和外部暴露位，可控制温度、CO2、湿度和O2，并支持振荡和条码读取。常用于细胞培养、高通量筛选和自动化工作站中的板管理。",
)
class CytomatBackend(IncubatorBackend):
  def __init__(self, *args, **kwargs):
    print("[UNILAB] CytomatBackend.__init__() called", flush=True)
    super().__init__(*args, **kwargs)
  default_baud = 9600
  serial_message_encoding = "utf-8"

  def __init__(self, model: Union[CytomatType, str], port: str):
    print("[UNILAB] CytomatBackend.__init__() called", flush=True)
    super().__init__()

    supported_models = [
      CytomatType.C6000,
      CytomatType.C6002,
      CytomatType.C2C_425,
      CytomatType.C2C_450_SHAKE,
      CytomatType.C5C,
    ]
    if isinstance(model, str):
      try:
        model = CytomatType(model)
      except ValueError:
        raise ValueError(f"Unsupported Cytomat model: '{model}'")
    if model not in supported_models:
      raise NotImplementedError(
        f"Only the following Cytomats are supported: {supported_models}, but got '{model}'"
      )
    self.model = model
    self._racks: List[PlateCarrier] = []

    self.io = Serial(
      port=port,
      baudrate=self.default_baud,
      bytesize=serial.EIGHTBITS,
      parity=serial.PARITY_NONE,
      stopbits=serial.STOPBITS_ONE,
      write_timeout=1,
      timeout=1,
    )

  @action(auto_prefix=True, description="准备设备以供运行。")
  async def setup(self):
    _unilab_logger.debug("[UNILAB] CytomatBackend.setup() called")
    await self.io.setup()
    await self.initialize()
    await self.wait_for_task_completion()

  @action(auto_prefix=True, description="设置设备中的板架布局。")
  async def set_racks(self, racks: List[PlateCarrier]):
    _unilab_logger.debug("[UNILAB] CytomatBackend.set_racks() called")
    await super().set_racks(racks)
    warnings.warn("Cytomat racks need to be configured with the exe software")

  @action(auto_prefix=True, description="停止设备运行。")
  async def stop(self):
    _unilab_logger.debug("[UNILAB] CytomatBackend.stop() called")
    await self.io.stop()

  def _assemble_command(self, command_type: str, command: str, params: str):
    _unilab_logger.debug("[UNILAB] CytomatBackend._assemble_command() called")
    carriage_return = "\r" if self.model == CytomatType.C2C_425 else "\r\n"
    command = f"{command_type}:{command} {params}".strip() + carriage_return
    return command

  @action(auto_prefix=True, description="向设备发送底层命令。")
  async def send_command(self, command_type: str, command: str, params: str) -> str:
    _unilab_logger.debug("[UNILAB] CytomatBackend.send_command() called")
    async def _send_command(command_str) -> str:
      _unilab_logger.debug("[UNILAB] CytomatBackend._send_command() called")
      logger.debug(command_str.encode(self.serial_message_encoding))
      await self.io.write(command_str.encode(self.serial_message_encoding))
      resp = (await self.io.read(128)).decode(self.serial_message_encoding)
      if len(resp) == 0:
        raise RuntimeError("Cytomat did not respond to command, is it turned on?")
      key, *values = resp.split()
      value = " ".join(values)

      if key == CytomatActionResponse.OK.value or key == command:
        # actions return an OK response, while checks return the command at the start of the response
        return value
      if key == CytomatActionResponse.ERROR.value:
        logger.error("Command %s failed with: '%s'", command_str, resp)
        if value == "03":
          error_register = await self.get_error_register()
          await self.reset_error_register()
          raise CytomatTelegramStructureError(f"Telegram structure error: {error_register}")
        if int(value, base=16) in error_map:
          await self.reset_error_register()
          raise error_map[int(value, base=16)]
        await self.reset_error_register()
        raise Exception(f"Unknown cytomat error code in response: {resp}")

      logger.error("Command %s received an unknown response: '%s'", command_str, resp)
      await self.reset_error_register()
      raise Exception(f"Unknown response from cytomat: {resp}")

    # Cytomats sometimes return a busy or command not recognized error even when the overview
    # register says the machine is not busy, or if the command is known. We will retry a few times,
    # which costs 1s if there is a true error, but is necessary to avoid false negatives.
    command_str = self._assemble_command(command_type=command_type, command=command, params=params)
    n_retries = 10
    exc: Optional[BaseException] = None
    for _ in range(n_retries):
      try:
        return await _send_command(command_str)
      except (CytomatCommandUnknownError, CytomatBusyError) as e:
        exc = e
        await asyncio.sleep(0.1)
        continue
    assert exc is not None
    await self.reset_error_register()
    raise exc

  @action(auto_prefix=True, description="向设备发送动作命令并等待完成。")
  async def send_action(
    self, command_type: str, command: str, params: str, timeout: Optional[int] = 60
  ) -> OverviewRegisterState:
    _unilab_logger.debug("[UNILAB] CytomatBackend.send_action() called")
    """Calls send_command, but has a timeout handler and returns the overview register state.
    Args:
      timeout: The maximum time to wait for the command to complete. If None, the command will not
        wait for completion.
    """
    await self.send_command(command_type, command, params)
    if timeout is not None:
      overview_register = await self.wait_for_task_completion(timeout=timeout)
    return overview_register

  def _site_to_firmware_string(self, site: PlateHolder) -> str:
    _unilab_logger.debug("[UNILAB] CytomatBackend._site_to_firmware_string() called")
    rack = cast(PlateCarrier, site.parent)
    rack_idx = [rack.name for rack in self._racks].index(
      rack.name
    )  # autoreload resistant, should work
    site_idx = next(idx for idx, s in rack.sites.items() if s == site)

    if self.model in [CytomatType.C2C_425]:
      return f"{str(rack_idx).zfill(2)} {str(site_idx).zfill(2)}"

    # TODO: configure all cytomats to use `rack site` format
    if self.model in [
      CytomatType.C6000,
      CytomatType.C6002,
      CytomatType.C2C_450_SHAKE,
      CytomatType.C5C,
    ]:
      slots_to_skip = sum(r.capacity for r in self._racks[:rack_idx])
      absolute_slot = slots_to_skip + site_idx + 1  # 1-indexed

      return f"{absolute_slot:03}"

    raise ValueError(f"Unsupported Cytomat model: {self.model}")

  @action(auto_prefix=True, description="获取总览寄存器状态。")
  async def get_overview_register(self) -> OverviewRegisterState:
    _unilab_logger.debug("[UNILAB] CytomatBackend.get_overview_register() called")
    # Sometimes this command is not recognized and it is not known why. We will retry a few times
    # We don't care if the cytomat is still busy, that is actually what we are often checking for.
    # We are just gathering state, so just try a little bit later.
    num_tries = 10
    for _ in range(num_tries):
      try:
        resp = await self.send_command("ch", "bs", "")
      except (CytomatCommandUnknownError, CytomatBusyError):
        await asyncio.sleep(0.1)
        continue
      return OverviewRegisterState.from_resp(resp)
    await self.reset_error_register()
    raise CytomatCommandUnknownError("Could not get overview register")

  @action(auto_prefix=True, description="获取警告寄存器状态。")
  async def get_warning_register(self) -> WarningRegister:
    _unilab_logger.debug("[UNILAB] CytomatBackend.get_warning_register() called")
    hex_value = await self.send_command("ch", "bw", "")
    for member in WarningRegister:
      if hex_value == member.value:
        return member

    await self.reset_error_register()
    raise Exception(f"Unknown warning register value: {hex_value}")

  @action(auto_prefix=True, description="获取错误寄存器状态。")
  async def get_error_register(self) -> ErrorRegister:
    _unilab_logger.debug("[UNILAB] CytomatBackend.get_error_register() called")
    hex_value = await self.send_command("ch", "be", "")
    for member in ErrorRegister:
      if hex_value == member.value:
        return member

    await self.reset_error_register()
    raise Exception(f"Unknown error register value: {hex_value}")

  @action(auto_prefix=True, description="复位错误寄存器。")
  async def reset_error_register(self) -> None:
    _unilab_logger.debug("[UNILAB] CytomatBackend.reset_error_register() called")
    await self.send_command("rs", "be", "")

  @action(auto_prefix=True, description="初始化设备。")
  async def initialize(self) -> None:
    _unilab_logger.debug("[UNILAB] CytomatBackend.initialize() called")
    await self.send_action("ll", "in", "", timeout=300)  # this command sometimes times out

  @action(auto_prefix=True, description="打开设备门。")
  async def open_door(self):
    _unilab_logger.debug("[UNILAB] CytomatBackend.open_door() called")
    return await self.send_action("ll", "gp", "002")

  @action(auto_prefix=True, description="关闭设备门。")
  async def close_door(self):
    _unilab_logger.debug("[UNILAB] CytomatBackend.close_door() called")
    return await self.send_action("ll", "gp", "001")

  @action(auto_prefix=True, description="收回传送铲。")
  async def shovel_in(self):
    _unilab_logger.debug("[UNILAB] CytomatBackend.shovel_in() called")
    return await self.send_action("ll", "sp", "001")

  @action(auto_prefix=True, description="伸出传送铲。")
  async def shovel_out(self):
    _unilab_logger.debug("[UNILAB] CytomatBackend.shovel_out() called")
    return await self.send_action("ll", "sp", "002")

  @action(auto_prefix=True, description="获取动作寄存器状态。")
  async def get_action_register(self) -> ActionRegisterState:
    _unilab_logger.debug("[UNILAB] CytomatBackend.get_action_register() called")
    hex_value = await self.send_command("ch", "ba", "")
    binary_repr = hex_to_binary(hex_value)
    target, action = binary_repr[:3], binary_repr[3:]

    target_enum = None
    for action_type_member in ActionType:
      if int(target, 2) == int(action_type_member.value, 16):
        target_enum = action_type_member
        break
    assert target_enum is not None, f"Unknown target value: {target}"

    action_enum = None
    for action_register_member in ActionRegister:
      if int(action, base=2) == int(action_register_member.value, base=16):
        action_enum = action_register_member
        break
    assert action_enum is not None, f"Unknown value: {action}"

    return ActionRegisterState(target=target_enum, action=action_enum)

  @action(auto_prefix=True, description="获取交换寄存器状态。")
  async def get_swap_register(self) -> SwapStationState:
    _unilab_logger.debug("[UNILAB] CytomatBackend.get_swap_register() called")
    value = await self.send_command("ch", "sw", "")
    return SwapStationState(
      position=SwapStationPosition(int(value[0])),
      load_status_front_of_gate=LoadStatusFrontOfGate(int(value[1])),
      load_status_at_processor=LoadStatusAtProcessor(int(value[2])),
    )

  @action(auto_prefix=True, description="获取传感器寄存器状态。")
  async def get_sensor_register(self) -> SensorStates:
    _unilab_logger.debug("[UNILAB] CytomatBackend.get_sensor_register() called")
    hex_value = await self.send_command("ch", "ts", "")
    binary_values = hex_to_base_twelve(hex_value)
    return SensorStates(
      **{member.name: bool(int(binary_values[member.value])) for member in SensorRegister}
    )

  @action(auto_prefix=True, description="将微孔板从传送位移入存储位。")
  async def action_transfer_to_storage(  # used by insert_plate
    self, site: PlateHolder
  ) -> OverviewRegisterState:
    _unilab_logger.debug("[UNILAB] CytomatBackend.action_transfer_to_storage() called")
    """Open lift door, retrieve from transfer, close door, place at storage"""
    return await self.send_action("mv", "ts", self._site_to_firmware_string(site), timeout=120)

  @action(auto_prefix=True, description="将微孔板从存储位送到传送位。")
  async def action_storage_to_transfer(  # used by retrieve_plate
    self, site: PlateHolder
  ) -> OverviewRegisterState:
    _unilab_logger.debug("[UNILAB] CytomatBackend.action_storage_to_transfer() called")
    """Retrieve from storage, open door, move to transfer, close door"""
    return await self.send_action("mv", "st", self._site_to_firmware_string(site))

  @action(auto_prefix=True, description="将微孔板从存储位送到等待位。")
  async def action_storage_to_wait(self, site: PlateHolder) -> OverviewRegisterState:
    _unilab_logger.debug("[UNILAB] CytomatBackend.action_storage_to_wait() called")
    """Retrieve from storage, move to wait position"""
    return await self.send_action("mv", "sw", self._site_to_firmware_string(site))

  @action(auto_prefix=True, description="将微孔板从等待位送回存储位。")
  async def action_wait_to_storage(self, site: PlateHolder) -> OverviewRegisterState:
    _unilab_logger.debug("[UNILAB] CytomatBackend.action_wait_to_storage() called")
    """Move from wait to storage, unload, return to wait"""
    return await self.send_action("mv", "ws", self._site_to_firmware_string(site))

  @action(auto_prefix=True, description="将微孔板从等待位送到传送位。")
  async def action_wait_to_transfer(self) -> OverviewRegisterState:
    _unilab_logger.debug("[UNILAB] CytomatBackend.action_wait_to_transfer() called")
    """Open door, place on transfer, return to wait, close door"""
    return await self.send_action("mv", "wt", "")

  @action(auto_prefix=True, description="将微孔板从传送位移到等待位。")
  async def action_transfer_to_wait(self) -> OverviewRegisterState:
    _unilab_logger.debug("[UNILAB] CytomatBackend.action_transfer_to_wait() called")
    """Open door, retrieve from transfer, return to wait, close door"""
    return await self.send_action("mv", "tw", "")

  @action(auto_prefix=True, description="将微孔板从等待位送到外部暴露位。")
  async def action_wait_to_exposed(self) -> OverviewRegisterState:
    _unilab_logger.debug("[UNILAB] CytomatBackend.action_wait_to_exposed() called")
    """Move from wait to exposed position outside device"""
    return await self.send_action("mv", "wh", "")

  @action(auto_prefix=True, description="将微孔板从外部暴露位送回等待位。")
  async def action_exposed_to_wait(self) -> OverviewRegisterState:
    _unilab_logger.debug("[UNILAB] CytomatBackend.action_exposed_to_wait() called")
    """Return to wait from exposed, close door"""
    return await self.send_action("mv", "hw", "")

  @action(auto_prefix=True, description="将微孔板从外部暴露位送回存储位。")
  async def action_exposed_to_storage(self, site: PlateHolder) -> OverviewRegisterState:
    _unilab_logger.debug("[UNILAB] CytomatBackend.action_exposed_to_storage() called")
    """Return with MTP from exposed to storage, move to wait, close door"""
    return await self.send_action("mv", "hs", self._site_to_firmware_string(site))

  @action(auto_prefix=True, description="将微孔板从存储位送到外部暴露位。")
  async def action_storage_to_exposed(self, site: PlateHolder) -> OverviewRegisterState:
    _unilab_logger.debug("[UNILAB] CytomatBackend.action_storage_to_exposed() called")
    """Move from wait to storage, load MTP, transport to exposed"""
    return await self.send_action("mv", "sh", self._site_to_firmware_string(site))

  @action(auto_prefix=True, description="读取指定存储位的条码。")
  async def action_read_barcode(
    self,
    site_number_a: str,
    site_number_b: str,
  ) -> OverviewRegisterState:
    _unilab_logger.debug("[UNILAB] CytomatBackend.action_read_barcode() called")
    # Read barcode of storage locations
    validate_storage_location_number(site_number_a)
    validate_storage_location_number(site_number_b)
    resp = await self.send_command("mv", "sn", f"{site_number_a} {site_number_b}")
    return OverviewRegisterState.from_resp(resp)

  @action(auto_prefix=True, description="等待传送位变为占用或空闲状态。")
  async def wait_for_transfer_station(self, occupied: bool = False):
    _unilab_logger.debug("[UNILAB] CytomatBackend.wait_for_transfer_station() called")
    """Wait for the transfer station to be occupied, or unoccupied."""
    while (await self.get_overview_register()).transfer_station_occupied != occupied:
      await asyncio.sleep(1)

  @action(auto_prefix=True, description="等待当前任务完成。")
  async def wait_for_task_completion(self, timeout=60) -> OverviewRegisterState:
    _unilab_logger.debug("[UNILAB] CytomatBackend.wait_for_task_completion() called")
    """
    Wait for the cytomat to finish the current task. This is done by checking the overview register
    until the busy bit is not set. If the cytomat is busy for too long, a TimeoutError is raised.
    If the error bit is set in the overview register, the error register is read and the corresponding
    error is raised.
    """
    start = time.time()
    while True:
      overview_register = await self.get_overview_register()
      if not overview_register.busy_bit_set:
        # only check for errors once the cytomat is done, so that the user has the chance to
        # handle the error and proceed if desired.
        if overview_register.error_register_set:
          error_register = await self.get_error_register()
          await self.reset_error_register()
          raise error_register_map[error_register]
        return overview_register
      await asyncio.sleep(1)
      if time.time() - start > timeout:
        raise TimeoutError("Cytomat did not complete task in time")

  @action(auto_prefix=True, description="初始化内部振荡模块。")
  async def init_shakers(self):
    _unilab_logger.debug("[UNILAB] CytomatBackend.init_shakers() called")
    return hex_to_binary(await self.send_command("ll", "vi", ""))

  @action(auto_prefix=True, description="按设定频率开始振荡。")
  async def start_shaking(self, frequency: float, shakers: Optional[List[int]] = None):
    _unilab_logger.debug("[UNILAB] CytomatBackend.start_shaking() called")
    if self.model == CytomatType.C5C:
      raise NotImplementedError("Shaking is not supported on this model")
    await self.set_shaking_frequency(frequency=int(frequency), shakers=shakers)
    return hex_to_binary(await self.send_command("ll", "va", ""))

  @action(auto_prefix=True, description="停止振荡。")
  async def stop_shaking(self):
    _unilab_logger.debug("[UNILAB] CytomatBackend.stop_shaking() called")
    if self.model == CytomatType.C5C:
      raise NotImplementedError("Shaking is not supported on this model")
    return hex_to_binary(await self.send_command("ll", "vd", ""))

  @action(auto_prefix=True, description="设置振荡频率。")
  async def set_shaking_frequency(
    self, frequency: int, shakers: Optional[List[int]] = None
  ) -> List[str]:
    _unilab_logger.debug("[UNILAB] CytomatBackend.set_shaking_frequency() called")
    shakers = shakers or [1, 2]
    assert all(shaker in [1, 2] for shaker in shakers), "Shaker index must be 1 or 2"
    return [await self.send_command("se", f"pb 2{idx-1}", f"{frequency:04}") for idx in shakers]

  @action(auto_prefix=True, description="获取指定培养查询值。")
  async def get_incubation_query(
    self, query: Literal["ic", "ih", "io", "it"]
  ) -> CytomatIncupationResponse:
    _unilab_logger.debug("[UNILAB] CytomatBackend.get_incubation_query() called")
    resp = await self.send_command("ch", query, "")
    nominal, actual = resp.split()
    return CytomatIncupationResponse(
      nominal_value=float(nominal.lstrip("+")), actual_value=float(actual.lstrip("+"))
    )

  @action(auto_prefix=True, description="获取CO2浓度。")
  async def get_co2(self) -> CytomatIncupationResponse:
    _unilab_logger.debug("[UNILAB] CytomatBackend.get_co2() called")
    return await self.get_incubation_query("ic")

  @action(auto_prefix=True, description="获取湿度。")
  async def get_humidity(self) -> CytomatIncupationResponse:
    _unilab_logger.debug("[UNILAB] CytomatBackend.get_humidity() called")
    return await self.get_incubation_query("ih")

  @action(auto_prefix=True, description="获取O2浓度。")
  async def get_o2(self) -> CytomatIncupationResponse:
    _unilab_logger.debug("[UNILAB] CytomatBackend.get_o2() called")
    return await self.get_incubation_query("io")

  @action(auto_prefix=True, description="获取温度。")
  async def get_temperature(self) -> float:
    _unilab_logger.debug("[UNILAB] CytomatBackend.get_temperature() called")
    return (await self.get_incubation_query("it")).actual_value

  @action(auto_prefix=True, description="将指定微孔板取到上样托盘。")
  async def fetch_plate_to_loading_tray(self, plate: Plate):
    _unilab_logger.debug("[UNILAB] CytomatBackend.fetch_plate_to_loading_tray() called")
    site = plate.parent
    assert isinstance(site, PlateHolder)
    await self.action_storage_to_transfer(site)

  @action(auto_prefix=True, description="将微孔板收入指定存储位。")
  async def take_in_plate(self, plate: Plate, site: PlateHolder):
    _unilab_logger.debug("[UNILAB] CytomatBackend.take_in_plate() called")
    await self.action_transfer_to_storage(site)

  @action(auto_prefix=True, description="设置温度。")
  async def set_temperature(self, *args, **kwargs):
    _unilab_logger.debug("[UNILAB] CytomatBackend.set_temperature() called")
    raise NotImplementedError("Temperature control is not implemented yet")

  @action(auto_prefix=True, description="导出设备配置或状态信息。")
  def serialize(self) -> dict:
    _unilab_logger.debug("[UNILAB] CytomatBackend.serialize() called")
    return {
      **IncubatorBackend.serialize(self),
      "model": self.model.value,
      "port": self.io.port,
    }


class CytomatChatterbox(CytomatBackend):
  async def setup(self):
    await self.wait_for_task_completion()

  async def stop(self):
    print("closing connection to cytomat")

  async def send_command(self, command_type, command, params):
    print(
      "cytomat", self._assemble_command(command_type=command_type, command=command, params=params)
    )
    if command_type == "ch":
      return "0"
    return "0" * 8

  async def wait_for_transfer_station(self, occupied: bool = False):
    # send the command, but don't wait when we are in chatting mode.
    _ = await self.get_overview_register()


# Deprecated alias with warning # TODO: remove mid May 2025 (giving people 1 month to update)
# https://github.com/PyLabRobot/pylabrobot/issues/466


class Cytomat:
  def __init__(self, *args, **kwargs):
    raise RuntimeError("`Cytomat` is deprecated. Please use `CytomatBackend` instead. ")
